### ISSUE TITLE
Fatal Error when trying to run "grunt" for building

### ISSUE THREAD

**Issue by ekan825-ndmp** [nmdp-bioinformatics/web-hml-fhir-converter#1]
![image](https://cloud.githubusercontent.com/assets/26445416/24666738/cec662e4-1926-11e7-877d-261b356f5a16.png)

**Comment by abrown3-nmdp** [comment]
This is an oddity with MS Windows 7, the web-hml-fhir-converter/spec folder can be renamed to 'mock'.  This will clear the issue for Windows development.
